name: API Test

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - run: pip install pytest requests playwright

      - run: pytest test_reqres_api.py -v

      - run: pytest API_Test.py -v
